/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prj_ecole;
import java.awt.Color;
import java.awt.Font;
import java.awt.SystemColor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author hp
 */
public class Gestion_prof extends javax.swing.JFrame {
   
    
    private int idProfesseur;
    /**
     * Creates new form Gestion_prof
     */
    public Gestion_prof(int idProfesseur) {
        initComponents();
        this.idProfesseur = idProfesseur;
        RemplirComboBoxClasse();
        RemplirSession();
        fetchProfInfo();
    }
 
   private void fetchProfInfo() {
        try {
            Connection cnx = Config.getConnection();
            cnx.setAutoCommit(true);

            String queryProf = "SELECT Nom, Prenom FROM Professeur WHERE Id_prof = ?";
            try (PreparedStatement cmdProf = cnx.prepareStatement(queryProf)) {
                cmdProf.setInt(1, this.idProfesseur);
                try (ResultSet reader = cmdProf.executeQuery()) {
                    if (reader.next()) {
                        String nom = reader.getString("Nom");
                        String prenom = reader.getString("Prenom");

                        label2.setText(nom + " " + prenom);
                        label2.setFont(new Font("Arial", Font.BOLD, 20));
                        label2.setForeground(Color.BLACK);
                    } else {
                        label2.setText("Informations du professeur non trouvées");
                        
                    }
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage());
        }
    }

    private void RemplirComboBoxClasse() {
        try {
        Connection cnx = Config.getConnection();
        cnx.setAutoCommit(true);

        String query = "Select distinct Nom_class from Class inner join Module on Module.Id_class = Class.Id_class inner join Professeur on Professeur.Id_prof = Module.Id_prof where Professeur.Id_prof = ?";
        try (PreparedStatement cmd = cnx.prepareStatement(query)) {
            cmd.setInt(1, this.idProfesseur);
            try (ResultSet rs = cmd.executeQuery()) {
                //creation d'un modele pour remplir le jcombobox1
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
                model.addElement("--choisir la classe--");
                while (rs.next()) {
                    model.addElement(rs.getString("Nom_class"));
                }
                jComboBox1.setModel(model);
                if (jComboBox1.getItemCount() > 1) {
                    jComboBox1.setSelectedIndex(-1);
                }
            }
        }
        
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fetchdata = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnSaveNotes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, -1, -1));

        jPanel1.setBackground(new java.awt.Color(77, 125, 202));

        jPanel2.setBackground(new java.awt.Color(98, 140, 209));

        jButton1.setText("Se Déconnecter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        label2.setText("jLabel3");
        label2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Bienvenue,");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 534, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 680));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("Espace de gestion des notes");

        fetchdata.setAutoCreateRowSorter(true);
        fetchdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom_Class", "Nom", "Prénom", "Nom_Module", "Session_exam", "Type_Exam", "Note"
            }
        ));
        fetchdata.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(fetchdata);

        jButton3.setBackground(new java.awt.Color(77, 125, 202));
        jButton3.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jButton3.setText("Modifier");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(77, 125, 202));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnSaveNotes.setBackground(new java.awt.Color(77, 125, 202));
        btnSaveNotes.setFont(new java.awt.Font("Segoe UI Black", 2, 14)); // NOI18N
        btnSaveNotes.setText("Chercher");
        btnSaveNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNotesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(118, 118, 118)
                .addComponent(jButton3)
                .addGap(467, 467, 467))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveNotes)
                .addGap(195, 195, 195))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(btnSaveNotes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1080, 680));

        setSize(new java.awt.Dimension(1278, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void RemplirSession() {
        try {
        Connection cnx = Config.getConnection();
        cnx.setAutoCommit(true);

        String query = "Select distinct Session_exam from Examen inner join Module on Module.Id_module = Examen.Id_module inner join Professeur on Professeur.Id_prof = Module.Id_prof where Professeur.Id_prof = ?";
        try (PreparedStatement cmd = cnx.prepareStatement(query)) {
            cmd.setInt(1, this.idProfesseur);
            try (ResultSet rs = cmd.executeQuery()) {
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
                model.addElement("--choisir la session--");
                while (rs.next()) {
                    model.addElement(rs.getString("Session_exam"));
                }
                jComboBox2.setModel(model);
                if (jComboBox2.getItemCount() > 1) {
                    jComboBox2.setSelectedIndex(-1);
                }
            }
        }
      
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage());
    }
    }
    private void RemplirComboBoxModule() {
       try {
           Connection cnx = Config.getConnection();
           cnx.setAutoCommit(true);

           String query = "SELECT DISTINCT Nom_module FROM Module "
                + "INNER JOIN Professeur ON Professeur.Id_prof = Module.Id_prof inner join Class on Class.Id_class = Module.Id_class inner join Examen on Examen.Id_module=Module.Id_module "
                + "WHERE Professeur.Id_prof = ? AND Examen.Session_exam = ? and Class.Nom_class = ?";

           try (PreparedStatement cmd = cnx.prepareStatement(query)) {
                cmd.setInt(1, this.idProfesseur);

            
               if (jComboBox2.getSelectedItem() != null && jComboBox1.getSelectedItem() != null) {
                  String selectedSession = jComboBox2.getSelectedItem().toString();
                  String selectedclass = jComboBox1.getSelectedItem().toString();
                  cmd.setString(2, selectedSession);
                  cmd.setString(3, selectedclass);
                  try (ResultSet rs = cmd.executeQuery()) {
                    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
                    while (rs.next()) {
                        model.addElement(rs.getString("Nom_module"));
                    }                    
                    if (model.getSize() > 0) {
                        model.insertElementAt("--choisir le module--", 0);
                    } else {
                        model.addElement("--choisir le module--");
                    }

                    jComboBox3.setModel(model);
                    jComboBox3.setSelectedIndex(-1); 
                  }
               } else {
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
                model.addElement("--choisir le module--");
                jComboBox3.setModel(model);
                jComboBox3.setSelectedIndex(-1); 
              }
            }
         } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage());

        
        ex.printStackTrace();
      }
    }
    private void RemplirExam() {
      try {
        Connection cnx = Config.getConnection();
        cnx.setAutoCommit(true);

        String query = "SELECT DISTINCT Type_exam FROM Examen "
                + "INNER JOIN Module ON Module.Id_module = Examen.Id_module"
                + " INNER JOIN Professeur ON Professeur.Id_prof = Module.Id_prof "
                + "WHERE Professeur.Id_prof = ? AND Examen.Session_exam=? and Module.Nom_module=?";

        try (PreparedStatement cmd = cnx.prepareStatement(query)) {
            cmd.setInt(1, this.idProfesseur);

            
            if (jComboBox2.getSelectedItem() != null && jComboBox3.getSelectedItem() != null) {
                String selectedSession = jComboBox2.getSelectedItem().toString();
                String selectedmodule = jComboBox3.getSelectedItem().toString();
                cmd.setString(2, selectedSession);
                cmd.setString(3, selectedmodule);
                try (ResultSet rs = cmd.executeQuery()) {
                    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
                    while (rs.next()) {
                        model.addElement(rs.getString("Type_exam"));
                    }

                    if (model.getSize() > 0) {
                        model.insertElementAt("--choisir le Type d'examen--", 0);
                    } else {
                        model.addElement("--choisir le Type d'examen--");
                    }

                    jComboBox4.setModel(model);
                    jComboBox4.setSelectedIndex(-1); 
                }
            } else {
                DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
                model.addElement("--choisir le Type d'examen--");
                jComboBox4.setModel(model);
                jComboBox4.setSelectedIndex(-1); 
            }
          }
       } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Une erreur s'est produite : " + ex.getMessage());
        ex.printStackTrace();
       }
   }


    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        RemplirComboBoxModule();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        RemplirExam();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void btnSaveNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNotesActionPerformed
        // TODO add your handling code here:
    DefaultTableModel model = new DefaultTableModel(); 
    model.setColumnIdentifiers(new Object[]{"Nom_class", "ID", "Nom", "Prénom", "Nom_module", "Session_exam", "ID_exam", "Type_exam","Note"});

    try {
        Connection cnx = Config.getConnection();
        
        //pour que chaque instruction sql sera validée automatiquement apres son execution
        cnx.setAutoCommit(true);

        String query = "SELECT Class.Nom_class, Etudiant.Id_etud, Etudiant.Nom, Etudiant.Prenom, Module.Nom_module, Examen.Session_exam, Examen.Id_exam, Examen.Type_exam, Note.Note "
                + "FROM Etudiant "
                + "INNER JOIN Class ON Etudiant.Id_class = Class.Id_class "
                + "INNER JOIN Module ON Class.Id_class = Module.Id_class "
                + "INNER JOIN Examen ON Examen.Id_module = Module.Id_module "
                + "LEFT JOIN Note ON Etudiant.Id_etud = Note.Id_etud AND Examen.Id_exam = Note.Id_exam "
                + "WHERE Nom_class LIKE ? AND Nom_module LIKE ? AND Session_exam LIKE ? AND Type_exam LIKE ?";

        try (PreparedStatement queryCommand = cnx.prepareStatement(query)) {
            queryCommand.setString(1, "%" + jComboBox1.getSelectedItem().toString() + "%");
            queryCommand.setString(2, "%" + jComboBox3.getSelectedItem().toString() + "%");
            queryCommand.setString(3, "%" + jComboBox2.getSelectedItem().toString() + "%");
            queryCommand.setString(4, "%" + jComboBox4.getSelectedItem().toString() + "%");

            ResultSet resultSet = queryCommand.executeQuery();

            while (resultSet.next()) {
                String nom = resultSet.getString("Nom_class");
                int id = resultSet.getInt("Id_etud");
                String name = resultSet.getString("Nom");
                String lastname = resultSet.getString("Prenom");
                String CIN = resultSet.getString("Nom_module");
                String Login = resultSet.getString("Session_exam");
                int password = resultSet.getInt("Id_exam");
                String spe = resultSet.getString("Type_exam");
                float noteValue = resultSet.getFloat("Note");
                String note = (resultSet.wasNull()) ? "" : (noteValue == (int) noteValue) ? String.valueOf((int) noteValue) : String.valueOf(noteValue);
                model.addRow(new Object[]{nom, id, name, lastname, CIN, Login, password, spe,note});
            }
            fetchdata.setModel(model);
            hideColumns(fetchdata, 1);
            hideColumns(fetchdata, 6);

            fetchdata.setSelectionBackground(SystemColor.activeCaption);
            fetchdata.setSelectionForeground(Color.BLUE);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Une erreur s'est produite ici: " + ex.getMessage());
    }

    }//GEN-LAST:event_btnSaveNotesActionPerformed
    private void hideColumns(JTable table, int columnIndex) {
    TableColumn column = table.getColumnModel().getColumn(columnIndex);
    column.setMinWidth(0);
    column.setMaxWidth(0);
    column.setWidth(0);
    column.setPreferredWidth(0);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
        Connection cnx = Config.getConnection();
        cnx.setAutoCommit(true);

        for (int row = 0; row < fetchdata.getRowCount(); row++) {
        
            int idEtudiant = (int) fetchdata.getValueAt(row, 1);
            int idExamen = (int) fetchdata.getValueAt(row, 6);
            Object noteValueObject = fetchdata.getValueAt(row, 8);
            
            if (noteValueObject != null && noteValueObject instanceof String) {
                
                String formattedNote = (String) noteValueObject;
                try {
                    float noteValue = Float.parseFloat(formattedNote);

                   
                    String insertNoteQuery = "INSERT INTO Note (Id_etud, Id_exam, Note) VALUES (?, ?, ?)";
                    try (PreparedStatement insertNoteCommand = cnx.prepareStatement(insertNoteQuery)) {
                     
                        insertNoteCommand.setInt(1, idEtudiant);
                        insertNoteCommand.setInt(2, idExamen);
                        insertNoteCommand.setFloat(3, noteValue);
                        insertNoteCommand.executeUpdate();
                        
                    }
                } catch (NumberFormatException e) {
                   
                    JOptionPane.showMessageDialog(this, "Erreur lors de la conversion de la note en nombre.");
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Les notes ont été ajouté avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException ex) {
       
        JOptionPane.showMessageDialog(this, "Une erreur s'est produite ici: " + ex.getMessage());
    }
       
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
        Connection cnx = Config.getConnection();
        cnx.setAutoCommit(true);

        
        for (int row = 0; row < fetchdata.getRowCount(); row++) {
            int idEtudiant = (int) fetchdata.getValueAt(row, 1);
            int idExamen = (int) fetchdata.getValueAt(row, 6);

            
            Object noteValueObject = fetchdata.getValueAt(row, 8);

            
            if (noteValueObject != null && noteValueObject instanceof String) {
                
               
                String formattedNote = (String) noteValueObject;
                try {
      
                      float noteValue = Float.parseFloat(formattedNote);

                      String updateNoteQuery = "UPDATE Note SET Note = ? WHERE Id_etud = ? AND Id_exam = ?";
                      try (PreparedStatement updateNoteCommand = cnx.prepareStatement(updateNoteQuery)) {
                           updateNoteCommand.setFloat(1, noteValue);
                           updateNoteCommand.setInt(2, idEtudiant);
                           updateNoteCommand.setInt(3, idExamen);

                           updateNoteCommand.executeUpdate();
                           
                          }
                      } catch (NumberFormatException e) {
                   
                    JOptionPane.showMessageDialog(this, "Erreur lors de la conversion de la note en nombre.");
                }
            }
        }
         JOptionPane.showMessageDialog(this, "Modification effectuée avec succès!", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException ex) {
       
        JOptionPane.showMessageDialog(this, "Une erreur s'est produite ici: " + ex.getMessage());
    }
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        this.dispose();
        connexion loginFrame = new connexion();
         loginFrame.setVisible(true);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void label2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_prof.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new Gestion_prof(0).setVisible(true);
        }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveNotes;
    private javax.swing.JTable fetchdata;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label2;
    // End of variables declaration//GEN-END:variables
}
